name: Deploy Azure Functions

on:
  push:
    branches:
      - main
    paths:
      - 'pathfinder-api/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: 'Resolve Project Dependencies'
      shell: bash
      run: |
        cd pathfinder-api
        npm ci
        npm run build

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'ks-pathfinder-api'
        slot-name: 'production'
        package: './pathfinder-api'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
